import type { ServiceDef } from './types'

// The organization's service registry: every system an automated step can call.
// Endpoints use example domains; the simulation never makes a network call.

export function seedServices(): ServiceDef[] {
  return [
    {
      id: 'svc_erp',
      name: 'ERP Financials',
      kind: 'rest',
      description: 'Purchase orders, receipts and payables in the ERP (OpenAPI 3.1).',
      endpoint: 'https://erp.example.org/api/v2',
      auth: 'oauth2',
      secretRef: 'erp-client-credentials',
      status: 'online',
      owner: 'Finance Systems',
      operations: [
        {
          id: 'op_erp_match',
          name: 'POST /purchase-orders/match',
          description: 'Find the open PO for an invoice and check quantities and price.',
          avgMinutes: 3,
          successRate: 0.97,
          outputs: [{ key: 'matched', label: 'PO matched', type: 'boolean', trueRate: 0.85 }],
        },
        { id: 'op_erp_post', name: 'POST /payables', description: 'Create the payable and schedule payment.', avgMinutes: 1, successRate: 0.99, outputs: [] },
        { id: 'op_erp_po', name: 'GET /purchase-orders/{po}', avgMinutes: 0.5, successRate: 0.98, outputs: [{ key: 'found', label: 'PO found', type: 'boolean', trueRate: 0.9 }] },
        { id: 'op_erp_receipt', name: 'GET /receipts?po={po}', avgMinutes: 0.5, successRate: 0.98, outputs: [{ key: 'received', label: 'Goods received', type: 'boolean', trueRate: 0.88 }] },
      ],
    },
    {
      id: 'svc_ocr',
      name: 'Document AI (OCR)',
      kind: 'worker',
      description: 'Registered worker pool that extracts fields from scanned documents. Workers poll the topic for jobs.',
      endpoint: 'topic: documents.extract',
      auth: 'mtls',
      concurrency: 6,
      status: 'online',
      owner: 'Platform team',
      operations: [
        {
          id: 'op_ocr_extract',
          name: 'extract-invoice',
          avgMinutes: 2,
          successRate: 0.97,
          outputs: [{ key: 'confidence', label: 'Extraction confidence', type: 'number', min: 62, max: 99 }],
        },
      ],
    },
    {
      id: 'svc_mail',
      name: 'Notifications',
      kind: 'email',
      description: 'Outbound email and SMS.',
      endpoint: 'smtp://relay.example.org',
      auth: 'api-key',
      secretRef: 'mail-relay-key',
      status: 'online',
      owner: 'Platform team',
      operations: [{ id: 'op_mail_send', name: 'send', avgMinutes: 0.2, successRate: 0.995, outputs: [] }],
    },
    {
      id: 'svc_records',
      name: 'Records Archive',
      kind: 'rest',
      description: 'Long-term records management (retention schedules, legal hold).',
      endpoint: 'https://records.example.org/api',
      auth: 'oauth2',
      secretRef: 'records-client',
      concurrency: 4,
      status: 'online',
      owner: 'Records Management',
      operations: [{ id: 'op_rec_put', name: 'PUT /documents/{id}', avgMinutes: 1, successRate: 0.96, outputs: [] }],
    },
    {
      id: 'svc_dealers',
      name: 'Dealer Quotes',
      kind: 'rest',
      description: 'State contract dealers return price quotes; replies take a while.',
      endpoint: 'https://quotes.dealers.example.com/v1',
      auth: 'api-key',
      secretRef: 'dealer-quotes-key',
      status: 'online',
      owner: 'Procurement',
      operations: [{ id: 'op_quote', name: 'POST /quotes', avgMinutes: 50, successRate: 0.9, outputs: [] }],
    },
    {
      id: 'svc_vision',
      name: 'Vision AI (GPU pool)',
      kind: 'worker',
      description: 'Object detection on camera snapshots. Two GPU workers poll the topic; each frame takes about a minute end to end.',
      endpoint: 'topic: vision.detect',
      auth: 'mtls',
      concurrency: 2,
      status: 'online',
      owner: 'Security Operations',
      operations: [
        {
          id: 'op_detect',
          name: 'detect-objects',
          avgMinutes: 1.1,
          successRate: 0.99,
          outputs: [
            { key: 'confidence', label: 'Confidence', type: 'number', min: 20, max: 99 },
            { key: 'label', label: 'Object', type: 'choice', options: ['Person', 'Person', 'Vehicle', 'Animal', 'Unknown'] },
          ],
        },
      ],
    },
    {
      id: 'svc_watchlist',
      name: 'Watchlist (MCP server)',
      kind: 'mcp',
      description: 'MCP server exposing watchlist tools to automated steps and agents.',
      endpoint: 'https://watchlist.example.org/mcp',
      auth: 'oauth2',
      secretRef: 'watchlist-mcp',
      status: 'online',
      owner: 'Security Operations',
      operations: [
        {
          id: 'op_wl_compare',
          name: 'watchlist.compare',
          description: 'Compare a face or plate crop against the active watchlist.',
          avgMinutes: 0.5,
          successRate: 0.98,
          outputs: [
            { key: 'hit', label: 'Watchlist hit', type: 'boolean', trueRate: 0.06 },
            { key: 'score', label: 'Match score', type: 'number', min: 0, max: 100 },
            { key: 'subject', label: 'Subject', type: 'text', options: ['Subject W-1182', 'Subject W-2047', 'Plate 7XKD-221', 'Subject W-0903', 'Plate 4MRT-908'] },
          ],
        },
      ],
    },
    {
      id: 'svc_vms',
      name: 'Video Management System',
      kind: 'rest',
      description: 'Camera inventory, live feeds and clip export.',
      endpoint: 'https://vms.example.org/api',
      auth: 'api-key',
      secretRef: 'vms-api-key',
      concurrency: 8,
      status: 'online',
      owner: 'Security Operations',
      operations: [
        { id: 'op_vms_neighbors', name: 'GET /cameras/{id}/neighbors', description: 'Cameras with a view of the same area.', avgMinutes: 0.3, successRate: 0.99, outputs: [] },
        { id: 'op_vms_clip', name: 'POST /clips', description: 'Export 30 seconds around the event.', avgMinutes: 1.5, successRate: 0.95, outputs: [{ key: 'ready', label: 'Clip ready', type: 'boolean', trueRate: 1 }] },
      ],
    },
    {
      id: 'svc_triage',
      name: 'Threat Triage Agent',
      kind: 'agent',
      description: 'AI agent that reviews detections, enrichment and history, then rates the threat with a rationale. Uses the Watchlist and VMS tools.',
      endpoint: 'agent://soc/threat-triage',
      auth: 'managed-identity',
      status: 'online',
      owner: 'Security Operations',
      operations: [
        {
          id: 'op_assess',
          name: 'assess-threat',
          avgMinutes: 0.8,
          successRate: 0.96,
          outputs: [{ key: 'threat', label: 'Threat level', type: 'choice', options: ['Low', 'Low', 'Low', 'Medium', 'Medium', 'High'] }],
        },
      ],
    },
    {
      id: 'svc_cad',
      name: 'CAD Dispatch',
      kind: 'rest',
      description: 'Computer-aided dispatch: opens incidents and tracks units.',
      endpoint: 'https://cad.example.org/api',
      auth: 'mtls',
      status: 'online',
      owner: 'Public Safety IT',
      operations: [{ id: 'op_cad_open', name: 'POST /incidents', avgMinutes: 0.3, successRate: 0.99, outputs: [{ key: 'incident', label: 'Incident number', type: 'text', options: ['CAD-26-04412', 'CAD-26-04413', 'CAD-26-04419', 'CAD-26-04425', 'CAD-26-04431'] }] }],
    },
    {
      id: 'svc_identity',
      name: 'Identity Provider (MCP)',
      kind: 'mcp',
      description: 'MCP tools for accounts and group membership in the directory.',
      endpoint: 'https://idp.example.org/mcp',
      auth: 'oauth2',
      secretRef: 'idp-mcp',
      status: 'online',
      owner: 'IT',
      operations: [{ id: 'op_id_create', name: 'users.create', avgMinutes: 0.5, successRate: 0.97, outputs: [] }],
    },
    {
      id: 'svc_classifier',
      name: 'Document Classifier Agent',
      kind: 'agent',
      description: 'Reads a submission and suggests its category with a confidence score.',
      endpoint: 'agent://intake/classify',
      auth: 'managed-identity',
      status: 'online',
      owner: 'Platform team',
      operations: [
        {
          id: 'op_classify',
          name: 'classify',
          avgMinutes: 0.4,
          successRate: 0.98,
          outputs: [
            { key: 'confidence', label: 'Confidence', type: 'number', min: 40, max: 99 },
            { key: 'category', label: 'Category', type: 'text', options: ['General', 'Billing', 'Complaint', 'Records request'] },
          ],
        },
      ],
    },
  ]
}
