import { outcome } from './seed-helpers'
import type { Template, UserStepData, WfEdge } from './types'

// Starter library of reusable subflows. Groups are left for the person using
// the template to pick (their organization's groups), so each comes in with a
// friendly "pick a group" check rather than someone else's org chart.

const people = (label: string, extra: Partial<UserStepData> = {}): UserStepData => ({
  label,
  distribution: 'queue',
  autoDistribute: true,
  distributeEveryMinutes: 30,
  avgMinutes: 20,
  slaHours: 24,
  outcomes: [outcome(`${label}_ok`, 'Approve', 85), outcome(`${label}_no`, 'Reject', 15, { requireComment: true })],
  fieldAccess: {},
  ...extra,
})

const edge = (id: string, source: string, target: string, data: WfEdge['data'] = {}, sourceHandle = 'r', targetHandle = 'l'): WfEdge => ({ id, source, target, sourceHandle, targetHandle, data })

export function seedTemplates(): Template[] {
  const created = '2026-09-30T12:00:00.000Z'
  return [
    {
      id: 'tpl_two_level',
      name: 'Two-level approval',
      description: 'A manager approves; anything over the limit also needs a director. Ends as Approved or Rejected.',
      category: 'Approvals',
      tags: ['approval', 'threshold'],
      builtIn: true,
      createdAt: created,
      fields: [
        { id: 't2_amount', label: 'Amount', type: 'currency', width: 'half', min: 100, max: 60000, required: true },
        { id: 't2_approver', label: 'Approved By', type: 'user', width: 'half', system: true },
      ],
      nodes: [
        { id: 'a_start', type: 'start', position: { x: 0, y: 140 }, data: { label: 'Submitted' } },
        {
          id: 'a_mgr',
          type: 'user',
          position: { x: 220, y: 110 },
          data: people('Manager approval', {
            distribution: 'load-balance',
            avgMinutes: 15,
            outcomes: [
              outcome('a_m_ok', 'Approve', 90, { actions: [{ id: 'a_set', kind: 'setField', fieldId: 't2_approver', value: '{currentUser}' }] }),
              outcome('a_m_no', 'Reject', 10, { requireComment: true }),
            ],
            fieldAccess: { t2_amount: 'read' },
          }),
        },
        { id: 'a_limit', type: 'decision', position: { x: 580, y: 80 }, data: { label: 'Over the limit?' } },
        {
          id: 'a_dir',
          type: 'user',
          position: { x: 760, y: 0 },
          data: people('Director approval', {
            distribution: 'direct',
            avgMinutes: 20,
            outcomes: [
              outcome('a_d_ok', 'Approve', 85, { actions: [{ id: 'a_set2', kind: 'setField', fieldId: 't2_approver', value: '{currentUser}' }] }),
              outcome('a_d_no', 'Reject', 15, { requireComment: true }),
            ],
            fieldAccess: { t2_amount: 'read' },
          }),
        },
        { id: 'a_ok', type: 'end', position: { x: 1120, y: 146 }, data: { label: 'Approved', result: 'completed', outcome: 'Approved' } },
        { id: 'a_no', type: 'end', position: { x: 790, y: 300 }, data: { label: 'Rejected', result: 'rejected', outcome: 'Rejected' } },
      ],
      edges: [
        edge('a_e1', 'a_start', 'a_mgr'),
        edge('a_e2', 'a_mgr', 'a_limit', { outcomeId: 'a_m_ok' }),
        edge('a_e3', 'a_mgr', 'a_no', { outcomeId: 'a_m_no' }, 'b', 'l'),
        edge('a_e4', 'a_limit', 'a_dir', { order: 0, condition: { match: 'all', rules: [{ id: 'a_r1', fieldId: 't2_amount', op: 'gt', value: 10000 }] } }, 't', 'l'),
        edge('a_e5', 'a_limit', 'a_ok', { isDefault: true, order: 1 }, 'r', 'l'),
        edge('a_e6', 'a_dir', 'a_ok', { outcomeId: 'a_d_ok' }, 'r', 't'),
        edge('a_e7', 'a_dir', 'a_no', { outcomeId: 'a_d_no' }, 'b', 't'),
      ],
    },
    {
      id: 'tpl_parallel_review',
      name: 'Parallel review',
      description: 'Legal and compliance review at the same time. Both must approve before final sign-off; a rejection from either stops the other.',
      category: 'Reviews',
      tags: ['parallel', 'legal', 'compliance'],
      builtIn: true,
      createdAt: created,
      fields: [
        { id: 'pr_doc', label: 'Document', type: 'attachment', width: 'half' },
        { id: 'pr_notes', label: 'Review Notes', type: 'textarea', width: 'full' },
      ],
      nodes: [
        { id: 'pr_start', type: 'start', position: { x: 0, y: 176 }, data: { label: 'Ready for review' } },
        { id: 'pr_split', type: 'split', position: { x: 210, y: 160 }, data: { label: 'Send to both', mode: 'all' } },
        { id: 'pr_legal', type: 'user', position: { x: 380, y: 40 }, data: people('Legal review', { fieldAccess: { pr_doc: 'read', pr_notes: 'edit' } }) },
        { id: 'pr_comp', type: 'user', position: { x: 380, y: 270 }, data: people('Compliance review', { fieldAccess: { pr_doc: 'read', pr_notes: 'edit' } }) },
        { id: 'pr_join', type: 'join', position: { x: 760, y: 160 }, data: { label: 'Both approved', mode: 'all' } },
        {
          id: 'pr_sign',
          type: 'user',
          position: { x: 920, y: 146 },
          data: people('Final sign-off', { distribution: 'direct', avgMinutes: 10, outcomes: [outcome('pr_s_ok', 'Sign off', 100)], fieldAccess: { pr_doc: 'read', pr_notes: 'read' } }),
        },
        { id: 'pr_ok', type: 'end', position: { x: 1280, y: 172 }, data: { label: 'Signed off', result: 'completed', outcome: 'Approved' } },
        { id: 'pr_no', type: 'end', position: { x: 780, y: 430 }, data: { label: 'Rejected', result: 'rejected', outcome: 'Rejected' } },
      ],
      edges: [
        edge('pr_e1', 'pr_start', 'pr_split'),
        edge('pr_e2', 'pr_split', 'pr_legal', {}, 't', 'l'),
        edge('pr_e3', 'pr_split', 'pr_comp', {}, 'b', 'l'),
        edge('pr_e4', 'pr_legal', 'pr_join', { outcomeId: 'Legal review_ok' }, 'r', 't'),
        edge('pr_e5', 'pr_comp', 'pr_join', { outcomeId: 'Compliance review_ok' }, 'r', 'b'),
        edge('pr_e6', 'pr_legal', 'pr_no', { outcomeId: 'Legal review_no' }, 'b', 't'),
        edge('pr_e7', 'pr_comp', 'pr_no', { outcomeId: 'Compliance review_no' }, 'b', 'l'),
        edge('pr_e8', 'pr_join', 'pr_sign'),
        edge('pr_e9', 'pr_sign', 'pr_ok', { outcomeId: 'pr_s_ok' }),
      ],
    },
    {
      id: 'tpl_onboarding',
      name: 'Employee onboarding',
      description: 'Accounts are created automatically while IT, Facilities and Payroll work in parallel; the hiring manager welcomes the new hire once everything is ready.',
      category: 'People',
      tags: ['parallel', 'HR', 'MCP'],
      builtIn: true,
      createdAt: created,
      fields: [
        { id: 'ob_start', label: 'Start Date', type: 'date', width: 'half', required: true },
        { id: 'ob_manager', label: 'Hiring Manager', type: 'user', width: 'half', required: true },
        { id: 'ob_email', label: 'Work Email', type: 'email', width: 'half', system: true },
      ],
      nodes: [
        { id: 'ob_s', type: 'start', position: { x: 0, y: 266 }, data: { label: 'Offer accepted' } },
        { id: 'ob_split', type: 'split', position: { x: 200, y: 250 }, data: { label: 'Kick off', mode: 'all' } },
        {
          id: 'ob_acct',
          type: 'auto',
          position: { x: 370, y: 20 },
          data: { label: 'Create accounts', avgMinutes: 1, actions: [], serviceId: 'svc_identity', operationId: 'op_id_create', retries: 2, onFailure: 'manual' },
        },
        { id: 'ob_laptop', type: 'user', position: { x: 370, y: 170 }, data: people('Prepare laptop', { avgMinutes: 45, slaHours: 48, outcomes: [outcome('ob_l_ok', 'Ready', 100)] }) },
        { id: 'ob_badge', type: 'user', position: { x: 370, y: 320 }, data: people('Issue badge', { avgMinutes: 15, slaHours: 48, outcomes: [outcome('ob_b_ok', 'Issued', 100)] }) },
        { id: 'ob_pay', type: 'user', position: { x: 370, y: 470 }, data: people('Payroll setup', { avgMinutes: 25, slaHours: 72, outcomes: [outcome('ob_p_ok', 'Done', 100)] }) },
        { id: 'ob_join', type: 'join', position: { x: 770, y: 250 }, data: { label: 'Ready for day one', mode: 'all' } },
        {
          id: 'ob_welcome',
          type: 'user',
          position: { x: 930, y: 236 },
          data: people('Manager welcome', { distribution: 'field', assigneeFieldId: 'ob_manager', avgMinutes: 30, outcomes: [outcome('ob_w_ok', 'Welcomed', 100)] }),
        },
        { id: 'ob_end', type: 'end', position: { x: 1290, y: 262 }, data: { label: 'Onboarded', result: 'completed', outcome: 'Onboarded' } },
      ],
      edges: [
        edge('ob_e1', 'ob_s', 'ob_split'),
        edge('ob_e2', 'ob_split', 'ob_acct', {}, 't', 'l'),
        edge('ob_e3', 'ob_split', 'ob_laptop', {}, 'r', 'l'),
        edge('ob_e4', 'ob_split', 'ob_badge', {}, 'r', 'l'),
        edge('ob_e5', 'ob_split', 'ob_pay', {}, 'b', 'l'),
        edge('ob_e6', 'ob_acct', 'ob_join', {}, 'r', 't'),
        edge('ob_e7', 'ob_laptop', 'ob_join', {}, 'r', 'l'),
        edge('ob_e8', 'ob_badge', 'ob_join', {}, 'r', 'l'),
        edge('ob_e9', 'ob_pay', 'ob_join', {}, 'r', 'b'),
        edge('ob_e10', 'ob_join', 'ob_welcome'),
        edge('ob_e11', 'ob_welcome', 'ob_end'),
      ],
    },
    {
      id: 'tpl_ai_hitl',
      name: 'AI triage with human review',
      description: 'An AI agent classifies each item. Confident answers go straight through; the rest go to a person, whose corrections are recorded.',
      category: 'AI',
      tags: ['agent', 'human-in-the-loop'],
      builtIn: true,
      createdAt: created,
      fields: [
        { id: 'ai_conf', label: 'AI Confidence', type: 'number', min: 0, max: 100, width: 'half', system: true },
        { id: 'ai_cat', label: 'Category', type: 'text', width: 'half', system: true },
      ],
      nodes: [
        { id: 'ai_s', type: 'start', position: { x: 0, y: 150 }, data: { label: 'Received' } },
        {
          id: 'ai_cls',
          type: 'auto',
          position: { x: 210, y: 147 },
          data: {
            label: 'AI classification',
            avgMinutes: 1,
            actions: [],
            serviceId: 'svc_classifier',
            operationId: 'op_classify',
            outputs: [
              { key: 'confidence', fieldId: 'ai_conf' },
              { key: 'category', fieldId: 'ai_cat' },
            ],
            retries: 1,
            onFailure: 'manual',
          },
        },
        { id: 'ai_dec', type: 'decision', position: { x: 510, y: 114 }, data: { label: 'Confident?' } },
        { id: 'ai_auto', type: 'end', position: { x: 760, y: 10 }, data: { label: 'Auto-routed', result: 'completed', outcome: 'Auto-routed' } },
        {
          id: 'ai_rev',
          type: 'user',
          position: { x: 720, y: 240 },
          data: people('Human review', {
            avgMinutes: 6,
            outcomes: [outcome('ai_r_ok', 'Confirm', 80), outcome('ai_r_fix', 'Correct category', 20)],
            fieldAccess: { ai_conf: 'read', ai_cat: 'edit' },
          }),
        },
        { id: 'ai_done', type: 'end', position: { x: 1080, y: 266 }, data: { label: 'Reviewed', result: 'completed', outcome: 'Reviewed' } },
      ],
      edges: [
        edge('ai_e1', 'ai_s', 'ai_cls'),
        edge('ai_e2', 'ai_cls', 'ai_dec'),
        edge('ai_e3', 'ai_dec', 'ai_auto', { order: 0, condition: { match: 'all', rules: [{ id: 'ai_r1', fieldId: 'ai_conf', op: 'gte', value: 85 }] } }, 't', 'l'),
        edge('ai_e4', 'ai_dec', 'ai_rev', { isDefault: true, order: 1 }, 'b', 'l'),
        edge('ai_e5', 'ai_rev', 'ai_done', { outcomeId: 'ai_r_ok' }),
        edge('ai_e6', 'ai_rev', 'ai_done', { outcomeId: 'ai_r_fix' }, 'b', 'b'),
      ],
    },
    {
      id: 'tpl_three_way',
      name: 'Three-way match',
      description: 'Fetch the purchase order and the goods receipt in parallel, then match them against the invoice. Mismatches go to a person.',
      category: 'Finance',
      tags: ['parallel', 'ERP', 'REST'],
      builtIn: true,
      createdAt: created,
      fields: [
        { id: 'tw_po', label: 'PO Number', type: 'text', width: 'half' },
        { id: 'tw_found', label: 'PO Found', type: 'boolean', width: 'half', system: true },
        { id: 'tw_received', label: 'Goods Received', type: 'boolean', width: 'half', system: true },
      ],
      nodes: [
        { id: 'tw_s', type: 'start', position: { x: 0, y: 206 }, data: { label: 'Invoice captured' } },
        { id: 'tw_split', type: 'split', position: { x: 200, y: 190 }, data: { label: 'Fetch both', mode: 'all' } },
        {
          id: 'tw_po_get',
          type: 'auto',
          position: { x: 370, y: 70 },
          data: { label: 'Fetch purchase order', avgMinutes: 1, actions: [], serviceId: 'svc_erp', operationId: 'op_erp_po', outputs: [{ key: 'found', fieldId: 'tw_found' }], retries: 1, onFailure: 'manual' },
        },
        {
          id: 'tw_gr_get',
          type: 'auto',
          position: { x: 370, y: 320 },
          data: { label: 'Fetch goods receipt', avgMinutes: 1, actions: [], serviceId: 'svc_erp', operationId: 'op_erp_receipt', outputs: [{ key: 'received', fieldId: 'tw_received' }], retries: 1, onFailure: 'manual' },
        },
        { id: 'tw_join', type: 'join', position: { x: 680, y: 190 }, data: { label: 'Both fetched', mode: 'all' } },
        { id: 'tw_dec', type: 'decision', position: { x: 840, y: 172 }, data: { label: 'Matched?' } },
        { id: 'tw_ok', type: 'end', position: { x: 1100, y: 70 }, data: { label: 'Matched', result: 'completed', outcome: 'Matched' } },
        {
          id: 'tw_fix',
          type: 'user',
          position: { x: 1060, y: 300 },
          data: people('Resolve mismatch', { avgMinutes: 25, outcomes: [outcome('tw_f_ok', 'Resolved', 75), outcome('tw_f_no', 'Reject', 25, { requireComment: true })], fieldAccess: { tw_po: 'edit' } }),
        },
        { id: 'tw_no', type: 'end', position: { x: 1420, y: 326 }, data: { label: 'Mismatch', result: 'rejected', outcome: 'Rejected' } },
      ],
      edges: [
        edge('tw_e1', 'tw_s', 'tw_split'),
        edge('tw_e2', 'tw_split', 'tw_po_get', {}, 't', 'l'),
        edge('tw_e3', 'tw_split', 'tw_gr_get', {}, 'b', 'l'),
        edge('tw_e4', 'tw_po_get', 'tw_join', {}, 'r', 't'),
        edge('tw_e5', 'tw_gr_get', 'tw_join', {}, 'r', 'b'),
        edge('tw_e6', 'tw_join', 'tw_dec'),
        edge(
          'tw_e7',
          'tw_dec',
          'tw_ok',
          {
            order: 0,
            condition: {
              match: 'all',
              rules: [
                { id: 'tw_r1', fieldId: 'tw_found', op: 'isTrue' },
                { id: 'tw_r2', fieldId: 'tw_received', op: 'isTrue' },
              ],
            },
          },
          't',
          'l',
        ),
        edge('tw_e8', 'tw_dec', 'tw_fix', { isDefault: true, order: 1 }, 'b', 'l'),
        edge('tw_e9', 'tw_fix', 'tw_ok', { outcomeId: 'tw_f_ok' }, 't', 'b'),
        edge('tw_e10', 'tw_fix', 'tw_no', { outcomeId: 'tw_f_no' }),
      ],
    },
    {
      id: 'tpl_incident',
      name: 'Incident report',
      description: 'The person who handled the incident writes it up (retain familiar), a commander reviews, and it is filed to records automatically.',
      category: 'Public safety',
      tags: ['retain familiar', 'records'],
      builtIn: true,
      createdAt: created,
      fields: [
        { id: 'ir_officer', label: 'Responding Officer', type: 'user', width: 'half', system: true },
        { id: 'ir_notes', label: 'Report', type: 'textarea', width: 'full', system: true },
      ],
      nodes: [
        { id: 'ir_s', type: 'start', position: { x: 0, y: 136 }, data: { label: 'Incident confirmed' } },
        {
          id: 'ir_write',
          type: 'user',
          position: { x: 230, y: 106 },
          data: people('Write incident report', {
            distribution: 'field',
            assigneeFieldId: 'ir_officer',
            avgMinutes: 30,
            slaHours: 8,
            outcomes: [outcome('ir_w_ok', 'Submit', 100)],
            fieldAccess: { ir_notes: 'edit', ir_officer: 'read' },
          }),
        },
        {
          id: 'ir_rev',
          type: 'user',
          position: { x: 600, y: 106 },
          data: people('Supervisor review', {
            distribution: 'load-balance',
            avgMinutes: 8,
            outcomes: [outcome('ir_r_ok', 'Approve', 85), outcome('ir_r_back', 'Return for changes', 15, { requireComment: true })],
            fieldAccess: { ir_notes: 'read', ir_officer: 'read' },
          }),
        },
        {
          id: 'ir_file',
          type: 'auto',
          position: { x: 970, y: 120 },
          data: { label: 'File to records', avgMinutes: 1, actions: [], serviceId: 'svc_records', operationId: 'op_rec_put', retries: 1, onFailure: 'manual' },
        },
        { id: 'ir_end', type: 'end', position: { x: 1280, y: 136 }, data: { label: 'Filed', result: 'completed', outcome: 'Filed' } },
      ],
      edges: [
        edge('ir_e1', 'ir_s', 'ir_write'),
        edge('ir_e2', 'ir_write', 'ir_rev', { outcomeId: 'ir_w_ok' }),
        edge('ir_e3', 'ir_rev', 'ir_file', { outcomeId: 'ir_r_ok' }),
        edge('ir_e4', 'ir_rev', 'ir_write', { outcomeId: 'ir_r_back' }, 'b', 'b'),
        edge('ir_e5', 'ir_file', 'ir_end'),
      ],
    },
  ]
}
