{{- if .Values.podDisruptionBudget.enabled }}
{{- range $name, $d := .Values.deployments }}
{{- if $d.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "modus.fullname" $ }}-{{ $name }}
  labels:
    {{- include "modus.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  maxUnavailable: {{ $.Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "modus.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $name }}
{{- end }}
{{- end }}
{{- end }}
